services:
  postgres:
    image: postgres:16-alpine3.22
    environment:
      POSTGRES_PASSWORD: secret123
      DB_HOST: 0.0.0.0
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432

volumes:
  postgres: