services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.8-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret123
    volumes:
      - 'mongodb:/data/db'
    ports:
      - 27017:27017

volumes:
  mongodb: